### ISSUE TITLE
Searching for account using Account Number

### ISSUE THREAD

**Issue by dishamodi0910** [kunalshah017/ATM-Simulator#16]
Don't search whether an account exists or not using the name as there are chances that more than 2 people would be there with the same name.
Try to use an account number as for every new user a new value of the account number would be assigned which would help them to uniquely identify the user. 

=>SRAND() can be used to achieve this.

**Comment by kunalshah017** [comment]
thank you for your suggestion.
I have added account number using randomisation, Now each user will be assigned an 7-digit random and different account number whenever an account is created.

Issue Fixed in #22 
Thank You ! Do Star the Repo if you liked it 
and Please do share your views and issues on the project your PR's are most welcomed
